### ISSUE TITLE
php connect

### ISSUE THREAD

**Issue by Oosterdijk** [jmmeijer/skoalle#1]
Hey @jmmeijer , 

Je hebt wel je dbconnect.php script in je repo gezet.
Maar niet het config.php script waar de multidimensionale array in zit waar je de data om te connecten vandaan haalt.

**Comment by jmmeijer** [comment]
Hallo Floris,

Dat klopt inderdaad, dit heb ik in de les ook vertelt, de configuratiebestanden moeten niet in de repository terechtkomen. Vaak staat er wel een leeg voorbeeldbestand van de config. Dit kan ik wel in de repo toevoegen.

Met vriendelijke groet,
Jesse Meijer

Van: Floris Oosterdijk [mailto:notifications@github.com]
Verzonden: donderdag 24 november 2016 12:17
Aan: jmmeijer/skoalle <skoalle@noreply.github.com>
CC: Jesse Meijer <j.m.meijer@outlook.com>; Mention <mention@noreply.github.com>
Onderwerp: [jmmeijer/skoalle] php connect (#1)


Hey @jmmeijer<https://github.com/jmmeijer> ,

Je hebt wel je dbconnect.php script in je repo gezet.
Maar niet het config.php script waar de multidimensionale array in zit waar je de data om te connecten vandaan haalt.

**Comment by Oosterdijk** [comment]
Duidelijk @jmmeijer  .

Aanleiding van mijn opmerking was omdat we dit "beveiligen" van een `dbconnect.php`script hebben besproken in een vorige les.

Als iemand dan wel zo een opmaak wil maken, is het opzich handig om er een direct voorbeeld bij te hebben als een reminder van hoe het ook alweer werkt. 

Bijvoorbeeld in plaats van de daadwerkelijke data iets in de trand van :

`dbhost = "host hier neerzetten";`

Geen kritiek, gewoon aan het meedenken!

**Comment by jmmeijer** [comment]
Hey Floris,

Ik heb een leeg config bestand toegevoegd. Dit kun je gebruiken als voorbeeld.

Meedenken (ook opbouwende kritiek) is altijd welkom!

Groetjes,
Jesse

Van: Floris Oosterdijk [mailto:notifications@github.com]
Verzonden: donderdag 24 november 2016 15:33
Aan: jmmeijer/skoalle <skoalle@noreply.github.com>
CC: Jesse Meijer <j.m.meijer@outlook.com>; Mention <mention@noreply.github.com>
Onderwerp: Re: [jmmeijer/skoalle] php connect (#1)


Duidelijk @jmmeijer<https://github.com/jmmeijer> .

Aanleiding van mijn opmerking was omdat we dit "beveiligen" van een dbconnect.phpscript hebben besproken in een vorige les.

Als iemand dan wel zo een opmaak wil maken, is het opzich handig om er een direct voorbeeld bij te hebben als een reminder van hoe het ook alweer werkt.

Bijvoorbeeld in plaats van de daadwerkelijke data iets in de trand van :

dbhost = "host hier neerzetten";

Geen kritiek, gewoon aan het meedenken!
